services:
  pf:
    build:
      context: pf
      target: deploy
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_DB=silver
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=thisisalocalnetworkserver
      # this variable doesn't load in next.js .env loader. Unlucky
      #- NEXTAUTH_SECRET=

    # i fixed next.js env loader // maybe i didnt
    env_file:
      - pf/.env.local
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:12-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    user: postgres
    environment:
      - POSTGRES_PASSWORD=thisisalocalnetworkserver
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

# Doesn't work Lol i cant be bothered
#  prisma-studio:
#    container_name: prisma-studio
#    ports:
#      - "5555:5555"
#    build:
#      context: pf
#      dockerfile: Dockerfile-prisma-studio
#    depends_on:
#      - db

#    proxy:
#      image: nginx
#      volumes:
#        - type: bind
#          source: ./proxy/nginx.conf
#          target: /etc/nginx/conf.d/default.conf
#          read_only: true
#      ports:
#        - 80:80
#      depends_on:
#        - pf

volumes:
  db-data: { }
